### ISSUE TITLE
Unable to load records for Store(WebStore)

### ISSUE THREAD

**Issue by ghost** [jlyon87/lwc-lookup#4]
For lookup drop-down I can fetch data for Account, Contact, Product. But unable to fetch data for Store(WebStore).
Is there any specific difference between the object for Store and the object for others like Account, Contact and Product?

Any help will be appreciated.

**Comment by justin-lyon** [comment]
I'm unfamiliar with the WebStore sobject. I see that it is related to B2B Commerce. This component will attempt to use SOQL, SOSL, and for recently viewed it will attempt to use a SOQL on RecentlyViewed by your SObject Type. 

If that isn't enough to help you trouble shoot it, someone here might be able to help further. 
https://discord.com/invite/sfxd
